-- SQL to service new General Report


-- POPULATION, GENDER, AGE, ETHNICITY and HEALTH
--- POPULATION
SELECT DISTINCT CONVERT(date, [Date])
FROM LondonPopulation

--- GENDER
--- AGE
--- ETHNICITY
SELECT DISTINCT CONVERT(date, [Date])
FROM LondonEthnicity

-- SELECT DISTINCT CONVERT(date, [Date])
-- FROM LondonFullEthnicgroup

--- HEALTH
SELECT DISTINCT CONVERT(date, [Date])
FROM LondonGeneralhealth

-- EMPLOYMNET AND EDUCATION
--- EDUCATION
SELECT DISTINCT date
FROM LondonQualification;


--- DATES OF DATA
SELECT DISTINCT CONVERT(date, [DATE]) AS [YEAR]
FROM LONDON_EARNINGS_ON
ORDER BY [YEAR] DESC
---
--- EMPLOYMENT
---
SELECT [LEO].[Date] 				       AS [Date]
	 , ROUND(AVG([LEO].[NUMBER_OF_JOBS]),0) AS [NUMBER_OF_JOBS_AVG]
	 , ROUND(MIN([LEO].[NUMBER_OF_JOBS]),0) AS [NUMBER_OF_JOBS_MIN]
	 , ROUND(MAX([LEO].[NUMBER_OF_JOBS]),0) AS [NUMBER_OF_JOBS_MAX]
	FROM LONDON_EARNINGS_ON LEO`
	WHERE   CONVERT(int, [LEO].[Date]) BETWEEN 2010 AND 2021
	GROUP BY [LEO].[Date]
	ORDER BY [LEO].[Date] DESC;

-- RANKED NUMBER OF JOBS BY BOROUGH in DATE range for LONDON BOROUGHS
WITH RANKED_EARNINGS_LONDON_ONS   AS (
	SELECT [LEO].[Date]           AS [Date]
	     , [LEO].[BOROUGH]        AS [BOROUGH]
	     , [LEO].[NUMBER_OF_JOBS] AS [MEAN_NUMBER_OF_JOBS_BOROUGH]
	     , ROW_NUMBER() OVER(
	     				PARTITION BY [Date] 
	     				ORDER BY [Date] DESC
	     				       , [LEO].[NUMBER_OF_JOBS] DESC) AS [RANK]
	FROM LONDON_EARNINGS_ON LEO
)
SELECT [REL].[Date]					       AS [Date]
     , [REL].[BOROUGH]                     AS [BOROUGH] 
     , [REL].[RANK]					       AS [RANK]
     , [REL].[MEAN_NUMBER_OF_JOBS_BOROUGH] AS [MEAN_NUMBER_OF_JOBS_BOROUGH]
FROM RANKED_EARNINGS_LONDON_ONS REL
WHERE CONVERT(int, [Date]) BETWEEN 2010 AND 2021
ORDER BY [Date] DESC, [RANK] ASC

---
--- EARNINGS
---

--- MAX, AVG and MIN in DATE range for LONDON BOROUGHS
SELECT [LEO].[Date] 				       AS [Date]
	 , ROUND(AVG([LEO].[MEAN_INCOME]),0) AS [CITY_MEAN_INCOME_GBP_AVG]
	 , ROUND(MIN([LEO].[MEAN_INCOME]),0) AS [CITY_MEAN_INCOME_GBP_MIN]
	 , ROUND(MAX([LEO].[MEAN_INCOME]),0) AS [CITY_MEAN_INCOME_GBP_MAX]
	FROM LONDON_EARNINGS_ON LEO
	WHERE   CONVERT(int, [LEO].[Date]) BETWEEN 2010 AND 2021
	GROUP BY [LEO].[Date]
	ORDER BY [LEO].[Date] ASC;

--- RANKED EARNINGS BY BOROUGH in DATE range for LONDON BOROUGHS
WITH RANKED_EARNINGS_LONDON_ONS  AS (
	SELECT [LEO].[Date]        AS [Date]
	     , [LEO].[BOROUGH]     AS [BOROUGH]
	     , [LEO].[MEAN_INCOME] AS [MEAN_INCOME_GBP_BOROUGH]
	     , ROW_NUMBER() OVER(
	     				PARTITION BY [Date] 
	     				ORDER BY [Date] DESC
	     				       , [LEO].[MEAN_INCOME] DESC) AS [RANK]
	FROM LONDON_EARNINGS_ON LEO
)
SELECT [REL].[Date]					 AS [Date]
     , [REL].[BOROUGH]                  AS [BOROUGH] 
     , [REL].[RANK]					 AS [RANK]
     , [REL].[MEAN_INCOME_GBP_BOROUGH]  AS [MEAN_INCOME_GBP_BOROUGH]
FROM RANKED_EARNINGS_LONDON_ONS REL
WHERE CONVERT(int, [Date]) BETWEEN 2010 AND 2021
ORDER BY [Date] DESC, [RANK] ASC

-- CRIME
--- CRIME

SELECT [LCR].[YEAR], [LCR].[LAD_CODE], [LCR].[LAD_NAME], SUM([LCR].[COUNT])
FROM LONDON_CRIME_LDS LCR
WHERE CONVERT(int, [LCR].[YEAR]) BETWEEN 2020 AND 2021
GROUP BY [LCR].[YEAR], [LCR].[LAD_CODE], [LCR].[LAD_NAME]
ORDER BY [LCR].[YEAR] DESC, SUM([LCR].[COUNT]) DESC;

SELECT * FROM LondonPopulation lp 

-- Population Totals at Ward Level for 2011
WITH X AS(
SELECT DISTINCT [LPC].[LAD],
                [LPC].[LAD_NAME],
                [LPC].[WARD_CODE],
                [LPC].[WARD_NAME],
                [LPO].[OAcode], 
                [LPO].[ALL],
FROM LondonPopulation LPO
    ,IDX_LONDONPOSTCODES LPC
WHERE [LPC].[OA] = [LPO].[OAcode]
)
SELECT [LAD],
       [LAD_NAME],
       [WARD_CODE],
       [WARD_NAME],
	   SUM(CONVERT(INT,[ALL]))
FROM X
GROUP BY [LAD],
         [LAD_NAME],
         [WARD_CODE],
         [WARD_NAME]
ORDER BY [LAD], [WARD_CODE]

-- Jobs in borough
SELECT [LEO].[LAD_CODE],
       [LEO].[BOROUGH],
       [LEO].[NUMBER_OF_JOBS]
FROM LONDON_EARNINGS_ON LEO
WHERE leo.[DATE] = '2021'
ORDER BY [LEO].[LAD_CODE]





SELECT COUNT([LCR].[DATE])
FROM LONDON_CRIME_LDS LCR; 

ALTER TABLE LONDON_CRIME_LDS ADD [YEAR] NVARCHAR(4);

SELECT LEFT(DATE,4) FROM LONDON_CRIME_LDS LCD

UPDATE LONDON_CRIME_LDS SET [YEAR] = LEFT(DATE,4);