name: sd_maps_reports
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - python-chromedriver-binary
  - chrome
  - pip
  - pip:
    - dataframe_image==0.1.1
    - python-docx==0.8.11
    - docx_mailmerge==0.5.0
    - folium==0.12.1.post1
    - fpdf==1.7.2
    - selenium==4.3.0
    - streamlit==1.10.0
    - pandas==1.4.1
    - webdriver_manager==3.8.1