name: sd_maps_reports
channels:
  - conda-forge
dependencies:
  - gecko
  - dataframe_image
  - docx
  - docx_mailmerge
  - folium
  - fpdf
  - mailmerge
  - numpy
  - pandas
  - python_docx
  - selenium
  - streamlit