name: sd_maps_reports
channles:
  - conda-forge
dependencies:
  - gecko
  - numpy==1.22.2
  - aiohttp==3.8.1
  - aiosignal==1.2.0
  - altair==4.2.0
  - anyio==3.5.0
  - appdirs==1.4.4
  - argon2-cffi==21.3.0
  - argon2-cffi-bindings==21.2.0
  - asttokens==2.0.5
  - async-generator==1.10
  - async-timeout==4.0.2
  - attrs==21.4.0
  - Automat==20.2.0
  - Babel==2.9.1
  - backcall==0.2.0
  - beautifulsoup4==4.10.0
  - black==22.1.0
  - bleach==4.1.0
  - blinker==1.4
  - branca==0.5.0
  - Brotli==1.0.9
  - bs4==0.0.1
  - cachetools==5.2.0
  - certifi==2021.10.8
  - cffi==1.15.0
  - charset-normalizer==2.0.11
  - chromedriver-install==1.0.3
  - click==8.0.3
  - colorama==0.4.4
  - commonmark==0.9.1
  - constantly==15.1.0
  - cryptography==36.0.1
  - cssselect==1.1.0
  - cssselect2==0.6.0
  - cycler==0.11.0
  - dataframe-image==0.1.1
  - debugpy==1.5.1
  - decorator==5.1.1
  - defusedxml==0.7.1
  - docopt==0.6.2
  - docx-mailmerge==0.5.0
  - entrypoints==0.4
  - et-xmlfile==1.1.0
  - executing==0.8.2
  - fake-useragent==0.1.11
  - Flask==2.1.2
  - folium==0.12.1.post1
  - fonttools==4.30.0
  - fpdf==1.7.2
  - frozenlist==1.3.0
  - gitdb==4.0.9
  - GitPython==3.1.27
  - gobject==0.1.0
  - graphviz==0.19.1
  - h11==0.13.0
  - h2==3.2.0
  - hpack==3.0.0
  - html5lib==1.1
  - hyperframe==5.2.0
  - hyperlink==21.0.0
  - idna==3.3
  - imbalanced-learn==0.9.0
  - importlib-metadata==4.10.1
  - incremental==21.3.0
  - ipykernel==6.8.0
  - ipython==8.0.1
  - ipython-genutils==0.2.0
  - ipywebrtc==0.6.0
  - ipywidgets==7.7.1
  - itemadapter==0.4.0
  - itemloaders==1.0.4
  - itsdangerous==2.1.2
  - jedi==0.18.1
  - Jinja2==3.0.3
  - jmespath==0.10.0
  - joblib==1.1.0
  - json5==0.9.6
  - jsonschema==4.4.0
  - jupyter-client==7.1.2
  - jupyter-core==4.9.1
  - jupyter-server==1.13.5
  - jupyterlab==3.2.9
  - jupyterlab-pygments==0.1.2
  - jupyterlab-server==2.10.3
  - jupyterlab-widgets==1.1.1
  - kds==0.1.3
  - kiwisolver==1.3.2
  - lxml==4.7.1
  - MarkupSafe==2.0.1
  - matplotlib==3.5.1
  - matplotlib-inline==0.1.3
  - mistune==0.8.4
  - mlxtend==0.20.0
  - multidict==6.0.2
  - mypy-extensions==0.4.3
  - nbclassic==0.3.5
  - nbclient==0.5.10
  - nbconvert==6.4.1
  - nbformat==5.1.3
  - nest-asyncio==1.5.4
  - notebook==6.4.8
  - notebook-as-pdf==0.5.0
  - numpy==1.22.2
  - openpyxl==3.0.10
  - outcome==1.1.0
  - packaging==21.3
  - pandas==1.4.1
  - pandocfilters==1.5.0
  - parse==1.19.0
  - parsel==1.6.0
  - parso==0.8.3
  - pathspec==0.9.0
  - pickleshare==0.7.5
  - Pillow==9.0.1
  - pipreqs==0.4.11
  - platformdirs==2.4.1
  - plotly==5.6.0
  - pprintpp==0.4.0
  - priority==1.3.0
  - prometheus-client==0.13.1
  - prompt-toolkit==3.0.26
  - Protego==0.1.16
  - protobuf==3.20.1
  - pure-eval==0.2.2
  - pyarrow==8.0.0
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pycparser==2.21
  - pydeck==0.7.1
  - PyDispatcher==2.0.5
  - pydyf==0.2.0
  - pyee==8.2.2
  - Pygments==2.11.2
  - Pympler==1.0.1
  - pyOpenSSL==22.0.0
  - pyparsing==3.0.7
  - PyPDF2==1.27.2
  - pyphen==0.12.0
  - pyppeteer==1.0.2
  - PyQt5==5.15.6
  - PyQt5-Qt5==5.15.2
  - PyQt5-sip==12.9.1
  - pyquery==1.4.3
  - pyrsistent==0.18.1
  - python-dateutil==2.8.2
  - python-docx==0.8.11
  - pytz==2021.3
  - pytz-deprecation-shim==0.1.0.post0
  - pywin32==303
  - pywinpty==1.1.6
  - pyzmq==22.3.0
  - queuelib==1.6.2
  - requests==2.27.1
  - requests-html==0.10.0
  - rich==12.4.4
  - scikit-learn==1.0.2
  - scikit-plot==0.3.7
  - scipy==1.8.0
  - Scrapy==2.5.1
  - scrapy-selenium==0.0.7
  - scrapy-splash==0.8.0
  - seaborn==0.11.2
  - selenium==4.1.0
  - semver==2.13.0
  - Send2Trash==1.8.0
  - service-identity==21.1.0
  - six==1.16.0
  - sklearn==0.0
  - smmap==5.0.0
  - sniffio==1.2.0
  - sortedcontainers==2.4.0
  - soupsieve==2.3.1
  - stack-data==0.1.4
  - streamlit==1.10.0
  - tenacity==8.0.1
  - terminado==0.13.1
  - testpath==0.5.0
  - threadpoolctl==3.1.0
  - tinycss2==1.1.1
  - toml==0.10.2
  - tomli==2.0.0
  - toolz==0.11.2
  - tornado==6.1
  - tqdm==4.62.3
  - traitlets==5.1.1
  - trio==0.19.0
  - trio-websocket==0.9.2
  - Twisted==22.1.0
  - twisted-iocpsupport==1.0.2
  - typing_extensions==4.0.1
  - tzdata==2022.1
  - tzlocal==4.2
  - urllib3==1.26.8
  - validators==0.20.0
  - w3lib==1.22.0
  - watchdog==2.1.9
  - wcwidth==0.2.5
  - weasyprint==56.0
  - webencodings==0.5.1
  - websocket-client==1.2.3
  - websockets==10.1
  - Werkzeug==2.1.2
  - widgetsnbextension==3.6.1
  - wsproto==1.0.0
  - yarg==0.1.9
  - yarl==1.7.2
  - zipp==3.7.0
  - zope.interface==5.4.0
  - zopfli==0.2.1