name: sd_maps_reports
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - python-chromedriver-binary=105
  - pip
  - pip:
    - statsmodels==0.13.2
    - dataframe_image==0.1.1
    - python-docx==0.8.11
    - docx_mailmerge==0.5.0
    - folium==0.12.1.post1
    - fpdf==1.7.2
    - selenium==4.3.0
    - pandas==1.4.1
    - webdriver_manager==3.8.1
    - pyodbc==4.0.34
    - seaborn==0.11.2
    - colorcet==3.0.0
    - matplotlib==3.5.1
    - numpy==1.22.2
    - scipy==1.8.0
    - streamlit==1.12.0
    - toml==0.10.2
    - Unidecode==1.3.4
    - cacheout==0.13.1
    - chromedriver-install==1.0.3
    - chromedriver-autoinstaller==0.4.0
    
    